[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.31"
clap = { version = "4.4.11", features = ["derive", "env"] }
common = { path = "../common" }
dotenv = "0.15.0"
env_logger = "0.10.1"
futures = "0.3.29"
lapin = "2.3.1"
log = "0.4.20"
octocrab = "0.32.0"
once_cell = "1.18.0"
reqwest = "0.11.22"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
teloxide = { version = "0.12.2", features = ["macros"] }
timeago = { version = "0.4.2", features = ["chrono"] }
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread", "process", "sync"] }
jsonwebtoken = "9"
gix = {version = "0.56", default-features = false, features = ["max-performance-safe", "revision"]}
gix-features = { version = "0.36.0", optional = true }
walkdir = "2.4.0"
abbs-meta-apml = { git = "https://github.com/AOSC-Dev/abbs-meta-rs", package = "abbs-meta-apml", rev = "4a592937b44e8bb93103edd34eff384169a3248a" }

[features]
default = ["gix-max-perf"]
# Enables most of the `max-performance` features of the `gix` module for better performance.
# This can be more difficult to build in some conditions and requires cmake.
gix-max-perf = ["gix-features/zlib-ng", "gix/fast-sha1"]
# Slower than `git-repository-max-perf`, but better than the default.
# Unlike `git-repository-max-perf` this does not require cmake and allows dynamic zlib linking.
gix-faster = ["gix-features/zlib-stock", "gix/fast-sha1"]
