[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
chrono = "0.4.34"
clap = { version = "4.5.1", features = ["derive", "env"] }
common = { path = "../common" }
dotenv = "0.15.0"
env_logger = "0.11.2"
futures = "0.3.30"
lapin = "2.3.1"
log = "0.4.20"
octocrab = "0.34.1"
once_cell = "1.19.0"
reqwest = "0.11.24"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
teloxide = { version = "0.12.2", features = ["macros"] }
timeago = { version = "0.4.2", features = ["chrono"] }
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread", "process", "sync"] }
console = "0.15.8"
buildit-utils = { path = "../buildit-utils" }
jsonwebtoken = "9.2.0"
size = "0.4.1"
dickens = { git = "https://github.com/AOSC-Dev/dickens.git", version = "0.1.0" }
deadpool-lapin = "0.11.0"
