[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.31"
clap = { version = "4.4.11", features = ["derive", "env"] }
common = { path = "../common" }
dotenv = "0.15.0"
env_logger = "0.10.1"
futures = "0.3.29"
lapin = "2.3.1"
log = "0.4.20"
octocrab = "0.32.0"
once_cell = "1.18.0"
reqwest = "0.11.22"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
teloxide = { version = "0.12.2", features = ["macros"] }
timeago = { version = "0.4.2", features = ["chrono"] }
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread", "process", "sync"] }
console = "0.15.7"
buildit-utils = { path = "../buildit-utils" }
jsonwebtoken = "9.2.0"
