name: Rust

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config libsystemd-dev liblzma-dev libdbus-1-dev

    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
